version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
    command: java -jar app.jar
    volumes:
      - .:/app
    networks:
      - my-network
networks:
  my-network:
